"""initial dedicated postgres schema

Revision ID: 09f08021a4b9
Revises: 
Create Date: 2026-08-26 13:09:18.423768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f08021a4b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_mapping',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('xano_order_id', sa.String(), nullable=False),
    sa.Column('movu_order_id', sa.String(), nullable=False),
    sa.Column('terminal_id', sa.String(), nullable=True),
    sa.Column('gate_id', sa.String(), nullable=True),
    sa.Column('current_state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_mapping_movu_order_id'), 'order_mapping', ['movu_order_id'], unique=True)
    op.create_index(op.f('ix_order_mapping_xano_order_id'), 'order_mapping', ['xano_order_id'], unique=False)
    op.create_table('preparation_run',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('package_count', sa.Integer(), nullable=True),
    sa.Column('pdf_uploaded', sa.Boolean(), nullable=False),
    sa.Column('pdf_filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preparation_run_pack',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('preparation_run_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('emplacement', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_movu_stocked', sa.Boolean(), nullable=True),
    sa.Column('movu_handling_unit_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('mission_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preparation_run_pack_preparation_run_id'), 'preparation_run_pack', ['preparation_run_id'], unique=False)
    op.create_table('retry_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_endpoint', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_log_notification_id'), 'webhook_log', ['notification_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_log_notification_id'), table_name='webhook_log')
    op.drop_table('webhook_log')
    op.drop_table('retry_queue')
    op.drop_index(op.f('ix_preparation_run_pack_preparation_run_id'), table_name='preparation_run_pack')
    op.drop_table('preparation_run_pack')
    op.drop_table('preparation_run')
    op.drop_index(op.f('ix_order_mapping_xano_order_id'), table_name='order_mapping')
    op.drop_index(op.f('ix_order_mapping_movu_order_id'), table_name='order_mapping')
    op.drop_table('order_mapping')
    # ### end Alembic commands ###
