"""add gate to inbound_requests

Revision ID: 139b369a6a2a
Revises: f98f0c4a926d
Create Date: 2026-08-27 08:44:07.122914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139b369a6a2a'
down_revision: Union[str, None] = 'f98f0c4a926d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound_requests', sa.Column('gate', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbound_requests', 'gate')
    # ### end Alembic commands ###
