"""add movu_order_id to preparation_run_pack

Revision ID: 47d5c5c2d383
Revises: 139b369a6a2a
Create Date: 2026-08-27 12:01:59.402013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47d5c5c2d383'
down_revision: Union[str, None] = '139b369a6a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preparation_run', sa.Column('detail_uploaded', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('preparation_run', sa.Column('detail_filename', sa.String(), nullable=True))
    op.drop_column('preparation_run', 'pdf_filename')
    op.drop_column('preparation_run', 'pdf_uploaded')
    op.add_column('preparation_run_pack', sa.Column('movu_order_id', sa.String(), nullable=True))
    op.drop_column('preparation_run_pack', 'mission_requested_at')
    op.drop_column('preparation_run_pack', 'delivered_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preparation_run_pack', sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('preparation_run_pack', sa.Column('mission_requested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('preparation_run_pack', 'movu_order_id')
    op.add_column('preparation_run', sa.Column('pdf_uploaded', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('preparation_run', sa.Column('pdf_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('preparation_run', 'detail_filename')
    op.drop_column('preparation_run', 'detail_uploaded')
    # ### end Alembic commands ###
