"""add user terminal and replenishment_requests table

Revision ID: 54cbbec151cc
Revises: b3a3a56ab275
Create Date: 2026-08-31 06:51:05.315926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54cbbec151cc'
down_revision: Union[str, None] = 'b3a3a56ab275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replenishment_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('handling_unit_id', sa.String(), nullable=False),
    sa.Column('movu_order_id', sa.String(), nullable=True),
    sa.Column('presented_terminal_id', sa.String(), nullable=True),
    sa.Column('presented_gate_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('requested_by_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replenishment_requests_handling_unit_id'), 'replenishment_requests', ['handling_unit_id'], unique=False)
    op.add_column('users', sa.Column('terminal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'terminal')
    op.drop_index(op.f('ix_replenishment_requests_handling_unit_id'), table_name='replenishment_requests')
    op.drop_table('replenishment_requests')
    # ### end Alembic commands ###
