"""add presented terminal/gate to preparation_run_pack

Revision ID: b3a3a56ab275
Revises: 47d5c5c2d383
Create Date: 2026-08-28 08:31:04.347829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a3a56ab275'
down_revision: Union[str, None] = '47d5c5c2d383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preparation_run_pack', sa.Column('presented_terminal_id', sa.String(), nullable=True))
    op.add_column('preparation_run_pack', sa.Column('presented_gate_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preparation_run_pack', 'presented_gate_id')
    op.drop_column('preparation_run_pack', 'presented_terminal_id')
    # ### end Alembic commands ###
