"""add user role, access_terminals array, encrypted_password

Revision ID: de6f158ac579
Revises: 54cbbec151cc
Create Date: 2026-08-31 07:13:22.588524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de6f158ac579'
down_revision: Union[str, None] = '54cbbec151cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('access_terminals', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False, server_default='user'))
    op.drop_column('users', 'terminal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terminal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'role')
    op.drop_column('users', 'access_terminals')
    op.drop_column('users', 'encrypted_password')
    # ### end Alembic commands ###
