"""add inbound_requests table

Revision ID: f98f0c4a926d
Revises: 5af6828d22ea
Create Date: 2026-08-27 07:13:59.072179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98f0c4a926d'
down_revision: Union[str, None] = '5af6828d22ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('handling_unit_id', sa.String(), nullable=False),
    sa.Column('movu_order_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('requested_by_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_requests_handling_unit_id'), 'inbound_requests', ['handling_unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inbound_requests_handling_unit_id'), table_name='inbound_requests')
    op.drop_table('inbound_requests')
    # ### end Alembic commands ###
