"""create middleware tables

Revision ID: fbaefda87a61
Revises: 
Create Date: 2026-08-24 14:56:33.856743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbaefda87a61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_mapping',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('xano_order_id', sa.String(), nullable=False),
    sa.Column('movu_order_id', sa.String(), nullable=False),
    sa.Column('terminal_id', sa.String(), nullable=True),
    sa.Column('gate_id', sa.String(), nullable=True),
    sa.Column('current_state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='middleware'
    )
    op.create_index(op.f('ix_middleware_order_mapping_movu_order_id'), 'order_mapping', ['movu_order_id'], unique=True, schema='middleware')
    op.create_index(op.f('ix_middleware_order_mapping_xano_order_id'), 'order_mapping', ['xano_order_id'], unique=False, schema='middleware')
    op.create_table('retry_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_endpoint', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='middleware'
    )
    op.create_table('webhook_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='middleware'
    )
    op.create_index(op.f('ix_middleware_webhook_log_notification_id'), 'webhook_log', ['notification_id'], unique=True, schema='middleware')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_middleware_webhook_log_notification_id'), table_name='webhook_log', schema='middleware')
    op.drop_table('webhook_log', schema='middleware')
    op.drop_table('retry_queue', schema='middleware')
    op.drop_index(op.f('ix_middleware_order_mapping_xano_order_id'), table_name='order_mapping', schema='middleware')
    op.drop_index(op.f('ix_middleware_order_mapping_movu_order_id'), table_name='order_mapping', schema='middleware')
    op.drop_table('order_mapping', schema='middleware')
    # ### end Alembic commands ###
